import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
// import styles from '../styles/Home.module.css'
import Link from "next/link";
import * as Style from "../styles/homeStyles";
import api from "../services/api";
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/pagination";
import { Pagination } from "swiper";
import { format } from "date-fns";
import { ptBR } from "date-fns/locale";
import { MOBILE_WIDTH } from "../src/utils/constants";
import useMediaQuery from "../src/hooks/useMediaQuery";
import Colunists from "../components/Colunists";
export async function getServerSideProps() {
  //const [autor, setAutor] = useState([]);
  const colunist = await api
    .get("https://kellek.com.br/wp-json/wp/v2/users?per_page=5&offset=1&_embed")
    .then((res) => {
      // api
      //   .get(`https://kellek.com.br/wp-json/wp/v2/users/${res[0].author}`)
      //   .then((response) => setAutor(response.data.name));
      return res.data;
    })
    .then((response) => {
      return response;
    });
  const swiperPost = await api
    .get("https://kellek.com.br/wp-json/wp/v2/posts?per_page=5&offset=1&_embed")
    .then((res) => {
      // api
      //   .get(`https://kellek.com.br/wp-json/wp/v2/users/${res[0].author}`)
      //   .then((response) => setAutor(response.data.name));
      return res.data;
    })
    .then((response) => {
      return response;
    });
  const post = await api
    .get("https://kellek.com.br/wp-json/wp/v2/posts?per_page=12&offset=1")
    .then((res) => {
      return res.data;
    })
    .then((response) => {
      return response;
    });
  return {
    props: {
      colunist,
      swiperPost,
      post,
    },
  };
}
// export async function getStaticProps() {
//   //const [autor, setAutor] = useState([]);
//   const colunist = await api
//     .get("https://kellek.com.br/wp-json/wp/v2/users?per_page=5&offset=1&_embed")
//     .then((res) => {
//       // api
//       //   .get(`https://kellek.com.br/wp-json/wp/v2/users/${res[0].author}`)
//       //   .then((response) => setAutor(response.data.name));
//       return res.data;
//     })
//     .then((response) => {
//       return response;
//     });

//   return {
//     props: {
//       colunist,

//     },
//   };
// }

// const getAuthor = (author_id) => {
//   api
//     .get(`https://kellek.com.br/wp-json/wp/v2/users/${author_id}`)
//     .then((response) => {
//       console.log(response.data.name);
//       return response.data.name;
//     });
// };

export default function Home({ colunist, post, swiperPost }) {
  // console.log(authorName);
  // console.log(swiperPost);
  const isMobile = useMediaQuery(MOBILE_WIDTH);
  return (
    <Style.AllWrapp isDesktop={!isMobile}>
      <Head>
        <title>Blog Cannalize</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Style.Article isDesktop={!isMobile}>
        <Style.TagsWrapp isDesktop={!isMobile}>
          <Style.Tags isDesktop={!isMobile}>
            <Link href="/">Todos</Link>
            <Link href="/">Todos</Link>
            <Link href="/">Todos</Link>
            <Link href="/">Todos</Link>
            <Link href="/">Todos</Link>
          </Style.Tags>
        </Style.TagsWrapp>
        <Style.Hero isDesktop={!isMobile}>
          <Style.HeroWrapp isDesktop={!isMobile}>
            <Swiper
              spaceBetween={50}
              slidesPerView={1}
              onSlideChange={() => console.log("slide change")}
              pagination={true}
              modules={[Pagination]}
              isDesktop={!isMobile}
            >
              {swiperPost.map(
                ({ title, excerpt, yoast_head_json, date_gmt, _embedded }) => (
                  <SwiperSlide key={title} isDesktop={!isMobile}>
                    <Style.HeroText isDesktop={!isMobile}>
                      <h1>{title.rendered}</h1>
                      <div
                        dangerouslySetInnerHTML={{ __html: excerpt.rendered }}
                      ></div>
                      {/* <span>
                      <div
                        dangerouslySetInnerHTML={{
                          __html: content.rendered,
                        }}
                      ></div>
                    </span> */}
                      <p>
                        <strong>
                          {format(
                            new Date(date_gmt),
                            `dd 'de' MMMM 'de' yyyy`,
                            { locale: ptBR }
                          )}
                          , por
                          <Link href="/">
                            <a>{_embedded?.author[0].name}</a>
                          </Link>
                          {/* <p>{getAuthor(author)}</p> */}
                        </strong>
                      </p>
                    </Style.HeroText>
                    <Style.HeroImg isDesktop={!isMobile}>
                      <Image
                        src={yoast_head_json.og_image[0].url}
                        layout="responsive"
                        width={100}
                        height={75}
                        alt="teste"
                      />
                    </Style.HeroImg>
                  </SwiperSlide>
                )
              )}
            </Swiper>
          </Style.HeroWrapp>
          {/* <Style.HeroText>
            <h1>O &apos;barato&apos; do canabidiol</h1>
            <p>
              Um bud vistoso, cheiroso e tricomado não dá a menor pinta de ce é
              careta. Mas é.
            </p>
            <span>
              Trata-se da cannabis in natura rica em Cannabidiol (BCD), também
              chamada de cannabis light, na Itália, por exemplo, onde é
              legalmente comercializada, engloba variedades de flores com até
              0,3% de THC.
            </span>
            <p>
              <strong>
                12 de janeiro de 2022, por <Link href="/">Smoke Buddies</Link>
              </strong>
            </p>
          </Style.HeroText>
          <Style.HeroImg>
            <Image
              src={yoast_head_json.og_image[0].url}
              layout="responsive"
              width={100}
              height={75}
              alt="teste"
            />
          </Style.HeroImg> */}
        </Style.Hero>
        <Style.Grid isDesktop={!isMobile}>
          {post.map(({ guid, title, yoast_head_json, slug }) => {
            return (
              <div key={slug}>
                <Link href={slug} slug={slug} id={guid}>
                  <div className="card">
                    <div>
                      <div>
                        <Image
                          src={yoast_head_json.og_image[0].url}
                          layout="responsive"
                          width={700}
                          height={475}
                        />
                      </div>
                      <h1>{title.rendered}</h1>
                    </div>
                    {/* <img src= alt="" /> */}
                  </div>
                </Link>
              </div>
            );
          })}
        </Style.Grid>
      </Style.Article>
      <Style.Aside isDesktop={!isMobile}>
        <div>
          <div>
            <header>
              <h1>Colunistas</h1>
            </header>
            <section>
              <ul>
                <Colunists colunist={colunist} />
              </ul>
            </section>
            <Link href="/">
              <a>Leia mais</a>
            </Link>
          </div>
        </div>
      </Style.Aside>
    </Style.AllWrapp>
  );
}
