import React from "react";
import Head from "next/head";
import Image from "next/image";
// import styles from '../styles/Home.module.css'
import Link from "next/link";
import * as Style from "../styles/homeStyles";

export async function getServerSideProps() {
  const post = await fetch("https://kellek.com.br/wp-json/wp/v2/posts")
    .then((res) => {
      return res.json();
    })
    .then((response) => {
      console.log(response);
      return response;
    });
  return {
    props: {
      post,
    },
  };
}

export default function Home({ post }) {
  return (
    <div>
      <Head>
        <title>Blog Cannalize</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Style.Tags>
          <Link href="/">Todos</Link>
          <Link href="/">Todos</Link>
          <Link href="/">Todos</Link>
          <Link href="/">Todos</Link>
          <Link href="/">Todos</Link>
        </Style.Tags>
        <Style.Hero>
          <Style.HeroText>
            <h1>O &apos;barato&apos; do canabidiol</h1>
            <p>
              Um bud vistoso, cheiroso e tricomado não dá a menor pinta de ce é
              careta. Mas é.
            </p>
            <span>
              Trata-se da cannabis in natura rica em Cannabidiol (BCD), também
              chamada de cannabis light, na Itália, por exemplo, onde é
              legalmente comercializada, engloba variedades de flores com até
              0,3% de THC.
            </span>
            <p>
              <strong>
                12 de janeiro de 2022, por <Link href="/">Smoke Buddies</Link>
              </strong>
            </p>
          </Style.HeroText>
          <Style.HeroImg>
            <Image
              src="/assets/img/test.png"
              layout="responsive"
              width={100}
              height={75}
              alt="teste"
            />
          </Style.HeroImg>
        </Style.Hero>
        <Style.Grid>
          {post.map(({ guid, title, yoast_head_json, slug }) => {
            return (
              <Link href={slug}>
                <div key={title} className="card">
                  <div>
                    <div>
                      <Image
                        src={yoast_head_json.og_image[0].url}
                        layout="responsive"
                        width={700}
                        height={475}
                      />
                    </div>
                    <h1>{title.rendered}</h1>
                  </div>
                  {/* <img src= alt="" /> */}
                </div>
              </Link>
            );
          })}
        </Style.Grid>
      </main>
    </div>
  );
}
