import Head from "next/head";
import Image from "next/image";
// import styles from '../styles/Home.module.css'
import * as Style from "../styles/homeStyles";
import React, { useState, useEffect } from "react";

export default function Home() {
  const [post, setPost] = useState([]);

  useEffect(() => {
    try {
      fetch("https://kellek.com.br/wp-json/wp/v2/posts")
        .then((res) => {
          return res.json();
        })
        .then((response) => {
          setPost(response);
          console.log(response);
          console.log(post);
        });
    } catch (error) {
      console.log(error);
    }
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Style.Grid>
          {/* 
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          Get started by editing <code>pages/index.js</code>
        </p>

        <div>
          <a href="https://nextjs.org/docs">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn">
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/canary/examples">
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
      
      <footer>
      <a
      href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
      target="_blank"
      rel="noopener noreferrer"
      >
      Powered by{" "}
      <span>
      <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
      </span>
      </a>
      </footer> 
    */}
          {post.map(({ title, yoast_head_json }) => {
            return (
              <div key={title}>
                <div>
                  <h1>{title.rendered}</h1>
                  <div>
                    <Image
                      src={yoast_head_json.og_image[0].url}
                      layout="responsive"
                      width={700}
                      height={475}
                    />
                  </div>
                </div>
                {/* <img src= alt="" /> */}
              </div>
            );
          })}
        </Style.Grid>
      </main>
    </div>
  );
}
